#
# Application name.
#
# Appears in:
# - Spring Boot logs
# - Actuator endpoints
# - monitoring tools
#
# Example startup log:
#
# :: Spring Boot :: (v4.0.6)
# Starting shop application...
#
spring.application.name=shop


#
# Enables SQL statement logging.
#
# Hibernate-generated SQL queries will be
# displayed in the console.
#
# Useful for:
# - debugging
# - learning SQL generation
# - understanding ORM behaviour
#
# Example output:
#
# select
#     p1_0.id,
#     p1_0.name,
#     p1_0.price
# from
#     product p1_0
#
logging.level.sql=DEBUG


#
# Formats SQL output for readability.
#
# Without this:
#
# select p1_0.id,p1_0.name,p1_0.price from product p1_0
#
# With this enabled:
#
# select
#     p1_0.id,
#     p1_0.name,
#     p1_0.price
# from
#     product p1_0
#
# Makes debugging and teaching much easier.
#
spring.jpa.properties.hibernate.format_sql=true
